spring:
  datasource:
    url: jdbc:postgresql://postgres:hDZmBXULWWggAAqCVnnsLYxtYVZaunls@postgres.railway.internal:5432/railway
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate