spring:
  datasource:
    url: jdbc:postgresql://nozomi.proxy.rlwy.net:26845/railway
    username: postgres
    password: awUdKeXnvRHPHMQMgHEIyHlYKkpJMlHF
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
